### ISSUE TITLE
Can't seem to use PCRE patterns with MParser

### ISSUE THREAD

**Issue by magv** [murmour/mparser#11]
Hi. I have a piece of code that used to work like so (schematically):
```
open MParser
let _ = regexp_substrings (Pcre.regexp ~flags:[`DOTALL;`UNGREEDY] "xxx")
```
This worked with MParser 1.0.1 and OCaml 4.05.x, but now (MParser 1.2.3, OCaml 4.10.0) it doesn't. First of all, I need to add `open MParser_PCRE`, but even then:
```
$ ocamlfind ocamlopt -o test test.ml -package mparser.pcre,pcre -linkpkg
3 |   let _ = regexp_substrings (Pcre.regexp ~flags:[`DOTALL;`UNGREEDY] "xxx")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type Pcre.regexp
       but an expression was expected of type MParser_PCRE.Regexp.t
```

Is this example supposed to work? How should one use Pcre patterns and flags with MParser?

My OCaml has become rusty over time, but `MParser_PCRE.Regexp.t` is defined as `Pcre.regexp`, so this error message just confuses me.

In fact, replacing `Pcre.regexp` with `Regexp.make` does make it work, except that `Regexp.make` does not support `~flags`. Moreover, `Regexp.make` is literally defined as
```
  let make pattern =
    Pcre.regexp ~iflags:compile_flags pattern
```
... but using `Pcre.regexp` in stead of it is not allowed?

**Comment by murmour** [comment]
Hello, Vitaly!

I'm afraid it's no longer possible to plug in an existing `Pcre.regexp`, as `MParser_PCRE.Regexp.t` is an abstract type (`MParser_Sig.Regexp.t`). Inside the implementation of `MParser_PCRE.Regexp` it truly is `Pcre.regexp`, but the implementation is hidden (abstracted away) from the client.

Don't lose hope: specify your options [inside the regular expression itself](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC13).

It's curious to learn that someone uses PCRE-specific features inside parsers: I was about to ~~drop this burden~~ remove this dependency altogether. :sweat_smile:

**Comment by magv** [comment]
Hi, Max. Yeah, embedding the flags is what I ended up doing. I'm not fond of this of course because I have other places that use `Pcre.split` and `Pcre.replace` directly, so now I have two separate sets of regexp objects, and both swear they've never met each other, even when I can clearly see identical birthmarks on their forearms. But anyway, embedding the flags is not too bad.

Deleting PCRE support would be rather painful for me, on the other hand. Even replacing it with some other engine would be painful, because as you might imagine rewriting any non-trivial regexp in a new syntax is just asking for trouble.

**Comment by murmour** [comment]
> Hi, Max. Yeah, embedding the flags is what I ended up doing. I'm not fond of this of course because I have other places that use Pcre.split and Pcre.replace directly, so now I have two separate sets of regexp objects, and both swear they've never met each other, even when I can clearly see identical birthmarks on their forearms. But anyway, embedding the flags is not too bad.

I can extend MParser_PCRE like this:
```ocaml
module Regexp: sig
  include MParser_Sig.Regexp
  val from_pcre: Pcre.regexp -> t
end
```
Will that do?

Please punch me in the head (by pinging) if I don't cut a minor release before next week.


> Deleting PCRE support would be rather painful for me, on the other hand. Even replacing it with some other engine would be painful, because as you might imagine rewriting any non-trivial regexp in a new syntax is just asking for trouble.

Note taken! PCRE support will survive, although the API may change.

**Comment by magv** [comment]
> ```OCaml
> module Regexp: sig
>   include MParser_Sig.Regexp
>   val from_pcre: Pcre.regexp -> t
> end
> ```
> Will that do?

It should, yeah. I'll put down my `Obj.magic` then. For now.

> Note taken! PCRE support will survive, although the API may change.

To tell you the truth, after updating my code I was hoping not touch it for the next 5 years at least---and still have it buildable all the while. I now see that you've wanted to do a major update for a few years now. So, ugh, I'm fine if you'll take your time :)
