### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by jpotier** [murmour/mparser#5]
I see the source code is commented, would it be possible to get an online documentation?

I find it difficult to use MParser without it, plus the old one is [still online](http://harnold.org/software/ocaml-base/doc/MParser.html) and inaccurate.

**Comment by cakeplus** [comment]
In the just released [1.2.1](https://github.com/cakeplus/mparser/releases/tag/1.2.1) I've enabled OASIS to produce the API reference. I have also specified the doc-generation part in OPAM metadata, but I'm not sure how the end user is supposed to trigger it (the feature is undocumented).

**Comment by cakeplus** [comment]
Is it enough for you to be able to build the HTML reference yourself, by running `ocaml setup.ml -doc` inside the MParser source tree; or would you like me to put the generated docs onto some public URL?

**Comment by cakeplus** [comment]
By the way, wouldn't it be cool if OPAM itself supported hosting `ocamldoc` output produced from the properly prepared packages, like MParser (from 1.2.1)? I should open an issue upstream about this.

**Comment by murmour** [comment]
> Is it enough for you to be able to build the HTML reference yourself, by running ocaml setup.ml -doc inside the MParser source tree; or would you like me to put the generated docs onto some public URL?

Please reopen the issue if you want me to upload the API reference to some public address.
